# -*- coding: utf-8 -*-

"""
swaggerpetstoreopenapi30

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderStatusEnum(object):

    """Implementation of the 'OrderStatus' enum.

    Order Status

    Attributes:
        PLACED: TODO: type description here.
        APPROVED: TODO: type description here.
        DELIVERED: TODO: type description here.

    """

    PLACED = 'placed'

    APPROVED = 'approved'

    DELIVERED = 'delivered'
