# -*- coding: utf-8 -*-

"""
swaggerpetstoreopenapi30

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from swaggerpetstoreopenapi30.api_helper import APIHelper


class PetControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(PetControllerTests, cls).setUpClass()
        cls.controller = cls.client.pet
        cls.response_catcher = cls.controller.http_call_back

    # Multiple status values can be provided with comma separated strings
    def test_find_pets_by_status(self):
        # Parameters for the API call
        status = 'available'

        # Perform the API call through the SDK function
        result = self.controller.find_pets_by_status(status)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
    def test_find_pets_by_tags(self):
        # Parameters for the API call
        tags = None

        # Perform the API call through the SDK function
        result = self.controller.find_pets_by_tags(tags)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


