# -*- coding: utf-8 -*-

"""
swaggerpetstoreopenapi30

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from swaggerpetstoreopenapi30.api_helper import APIHelper
from swaggerpetstoreopenapi30.models.user import User


class UserControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(UserControllerTests, cls).setUpClass()
        cls.controller = cls.client.user
        cls.response_catcher = cls.controller.http_call_back

    # Creates list of users with given input array
    def test_create_users_with_list_input(self):
        # Parameters for the API call
        body = None

        # Perform the API call through the SDK function
        result = self.controller.create_users_with_list_input(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # Logs user into the system
    def test_login_user(self):
        # Parameters for the API call
        username = None
        password = None

        # Perform the API call through the SDK function
        result = self.controller.login_user(username, password)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['x-rate-limit'] = None
        expected_headers['x-expires-after'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


